## Basics of TF 2.0

In [1]:
import numpy as np
import tensorflow as tf

### .npz format (TensorFlow friendly file format)

In [2]:
x = np.arange(10)
y = np.arange(100)
z = np.random.uniform(0, 10, 25)

In [3]:
np.savez("sample_npz", x=x, y=y, z=z)

In [7]:
npz_file = np.load("sample_npz.npz")
npz_file.files

['x', 'y', 'z']

In [9]:
npz_file["z"]

array([7.91424318, 3.29565086, 3.40467184, 1.92107453, 7.076774  ,
       1.14763056, 1.31839866, 9.64820022, 6.68835225, 1.74474606,
       0.83840597, 0.48958693, 7.88907303, 0.18057739, 4.94738106,
       4.02162436, 6.42991382, 5.3334803 , 3.47304226, 7.15244775,
       2.89827227, 8.43167145, 1.70277271, 7.25336934, 4.89889945])

### Generate random data

In [11]:
observations = 1000
x1 = np.random.uniform(-10, 10, observations)
x2 = np.random.uniform(-10, 10, observations)

x = np.column_stack((x1, x2))

noise = np.random.uniform(-1, 1, observations)

y = 2*x1 - 3*x2 + 5 + noise

# save as a .npz file
np.savez("training_file", data = x, targets = y)

### Load data

In [13]:
training_data = np.load("training_file.npz")
x = training_data["data"]
y = training_data["targets"]

### Create tf model

In [19]:
output_size = 1
input_size = 2

model = tf.keras.Sequential([
    tf.keras.layers.Dense(output_size, activation=None)    
])

model.compile(optimizer="sgd", loss="mean_squared_error")
model.fit(x, y, epochs=10, verbose=2)

Train on 1000 samples
Epoch 1/10
1000/1000 - 0s - loss: 24.7429
Epoch 2/10
1000/1000 - 0s - loss: 4.4632
Epoch 3/10
1000/1000 - 0s - loss: 1.4795
Epoch 4/10
1000/1000 - 0s - loss: 0.6612
Epoch 5/10
1000/1000 - 0s - loss: 0.4388
Epoch 6/10
1000/1000 - 0s - loss: 0.3656
Epoch 7/10
1000/1000 - 0s - loss: 0.3511
Epoch 8/10
1000/1000 - 0s - loss: 0.3521
Epoch 9/10
1000/1000 - 0s - loss: 0.3530
Epoch 10/10
1000/1000 - 0s - loss: 0.3498


In [22]:
params = model.layers[0].get_weights()

In [23]:
weights = params[0]
bias = params[1]

In [24]:
weights

array([[ 1.9987478],
       [-2.9918811]], dtype=float32)

In [25]:
bias

array([4.991157], dtype=float32)

In [28]:
model.predict_on_batch(x).round(1)[:10]

array([[ 37.6],
       [ 10.4],
       [ -5.6],
       [ -5.9],
       [ 27.4],
       [ 22.4],
       [ 14.9],
       [ 35.8],
       [  0.7],
       [-10.4]], dtype=float32)

In [29]:
y.round(1)[:10]

array([ 37.5,  11.2,  -4.8,  -6. ,  27.5,  22.6,  15.3,  35.3,   0.6,
       -10.5])